version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: unistudy-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: unistudy-db
      MYSQL_USER: unistudy-app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
